name: Test idp package

on:
  pull_request:
    paths:
      - "packages/idp/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci
        working-directory: packages/idp

      - name: Build
        run: npm run build
        working-directory: packages/idp

      - name: Test
        run: npm test
        working-directory: packages/idp
